Updated Usage with Create React App - avoiding #71
Using jest-enzyme@3.0.0+ with Create React App is causing "TypeError: expect.addSnapshotSerializer is not a function" error.
This is happening because jest-enzyme@3.0.0+ depends on jest@19.0.0 while Create React App is currently using jest@18.1.0.
Added README warning - pending to be modified when Create React App updates their Jest dependency.

See also #71.